"""Domain model — the shared vocabulary across every service.

Add fields here rather than passing loose dicts between services. If two services
disagree about what a "meeting" is, the model is wrong.
"""

from .artifacts import (
    FILENAMES,
    Artifact,
    ArtifactKind,
    ExportManifest,
    ExportResult,
    ExportStatus,
    ManifestEntry,
)
from .chat import (
    AnswerStatus,
    ChatTurn,
    Chunk,
    Citation,
    CitedAnswer,
    Filters,
    Scope,
)
from .coaching import (
    RUBRICS,
    CoachingAssessment,
    CoachingDigest,
    CoachingTrack,
    DocumentRef,
    Drill,
    DrillKind,
    RubricScore,
)
from .common import (
    Cited,
    DateRange,
    ModelTier,
    SectionStatus,
    StageStatus,
    TranscriptSpan,
)
from .insights import (
    ActionItem,
    ActionStatus,
    Altitude,
    CommitmentType,
    Decision,
    Disagreement,
    DueDate,
    MeetingInsights,
    MindMap,
    MindMapNode,
    NodeType,
    Question,
    Risk,
)
from .meeting import (
    AudioQuality,
    AudioRef,
    ExternalRef,
    Meeting,
    MeetingSource,
    Participant,
    ProcessingStatus,
    SpeakerSource,
    SpeakerTurn,
    Transcript,
    TranscriptSegment,
    TranscriptSource,
)
from .speaker import (
    ConsentRecord,
    ConsentScope,
    Speaker,
    Voiceprint,
    VoiceprintLibrary,
)

__all__ = [
    "FILENAMES",
    "RUBRICS",
    "ActionItem",
    "ActionStatus",
    "Altitude",
    "AnswerStatus",
    "Artifact",
    "ArtifactKind",
    "AudioQuality",
    "AudioRef",
    "ChatTurn",
    "Chunk",
    "Citation",
    "Cited",
    "CitedAnswer",
    "CoachingAssessment",
    "CoachingDigest",
    "CoachingTrack",
    "CommitmentType",
    "ConsentRecord",
    "ConsentScope",
    "DateRange",
    "Decision",
    "Disagreement",
    "DocumentRef",
    "Drill",
    "DrillKind",
    "DueDate",
    "ExportManifest",
    "ExternalRef",
    "ExportResult",
    "ExportStatus",
    "Filters",
    "ManifestEntry",
    "Meeting",
    "MeetingInsights",
    "MeetingSource",
    "MindMap",
    "MindMapNode",
    "ModelTier",
    "NodeType",
    "Participant",
    "ProcessingStatus",
    "Question",
    "Risk",
    "RubricScore",
    "Scope",
    "SectionStatus",
    "Speaker",
    "SpeakerSource",
    "SpeakerTurn",
    "StageStatus",
    "Transcript",
    "TranscriptSegment",
    "TranscriptSource",
    "TranscriptSpan",
    "Voiceprint",
    "VoiceprintLibrary",
]
