"""initial_tables

Revision ID: 7ecad8854822
Revises: 
Create Date: 2026-03-26 17:01:25.897682

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7ecad8854822'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('a2a_messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('message_id', sa.String(length=256), nullable=False),
    sa.Column('sender', sa.String(length=128), nullable=False),
    sa.Column('receiver', sa.String(length=128), nullable=False),
    sa.Column('message_type', sa.String(length=64), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('content', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('correlation_id', sa.String(length=256), nullable=True),
    sa.Column('response_time_ms', sa.Float(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('message_id')
    )
    op.create_index(op.f('ix_a2a_messages_correlation_id'), 'a2a_messages', ['correlation_id'], unique=False)
    op.create_index(op.f('ix_a2a_messages_message_type'), 'a2a_messages', ['message_type'], unique=False)
    op.create_index(op.f('ix_a2a_messages_receiver'), 'a2a_messages', ['receiver'], unique=False)
    op.create_index(op.f('ix_a2a_messages_sender'), 'a2a_messages', ['sender'], unique=False)
    op.create_index(op.f('ix_a2a_messages_timestamp'), 'a2a_messages', ['timestamp'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.String(length=128), nullable=False),
    sa.Column('agent_id', sa.String(length=128), nullable=True),
    sa.Column('correlation_id', sa.String(length=256), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_agent_id'), 'audit_logs', ['agent_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_correlation_id'), 'audit_logs', ['correlation_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_event_type'), 'audit_logs', ['event_type'], unique=False)
    op.create_index(op.f('ix_audit_logs_timestamp'), 'audit_logs', ['timestamp'], unique=False)
    op.create_table('generations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('topic', sa.String(length=512), nullable=False),
    sa.Column('workflow_type', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('html_content', sa.Text(), nullable=True),
    sa.Column('file_path', sa.String(length=1024), nullable=True),
    sa.Column('total_duration_ms', sa.Float(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_generations_created', 'generations', ['created_at'], unique=False)
    op.create_index('ix_generations_status', 'generations', ['status'], unique=False)
    op.create_index(op.f('ix_generations_topic'), 'generations', ['topic'], unique=False)
    op.create_table('generation_steps',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('generation_id', sa.UUID(), nullable=False),
    sa.Column('step_number', sa.Integer(), nullable=False),
    sa.Column('agent_id', sa.String(length=128), nullable=False),
    sa.Column('task_type', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('result_summary', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_ms', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['generation_id'], ['generations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_generation_steps_generation_id'), 'generation_steps', ['generation_id'], unique=False)
    op.create_index('ix_genstep_gen_step', 'generation_steps', ['generation_id', 'step_number'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_genstep_gen_step', table_name='generation_steps')
    op.drop_index(op.f('ix_generation_steps_generation_id'), table_name='generation_steps')
    op.drop_table('generation_steps')
    op.drop_index(op.f('ix_generations_topic'), table_name='generations')
    op.drop_index('ix_generations_status', table_name='generations')
    op.drop_index('ix_generations_created', table_name='generations')
    op.drop_table('generations')
    op.drop_index(op.f('ix_audit_logs_timestamp'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_event_type'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_correlation_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_agent_id'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_a2a_messages_timestamp'), table_name='a2a_messages')
    op.drop_index(op.f('ix_a2a_messages_sender'), table_name='a2a_messages')
    op.drop_index(op.f('ix_a2a_messages_receiver'), table_name='a2a_messages')
    op.drop_index(op.f('ix_a2a_messages_message_type'), table_name='a2a_messages')
    op.drop_index(op.f('ix_a2a_messages_correlation_id'), table_name='a2a_messages')
    op.drop_table('a2a_messages')
    # ### end Alembic commands ###
