"""Artifact export.

``StubStorageService`` writes the identical folder contract to a local directory, so
naming, idempotency, hash-skip, and manifest handling are all exercised offline. Get
the behaviour right here; the Drive client is then a thin adapter with no logic of
its own.

See docs/capabilities/01-drive-export.md.
"""

from __future__ import annotations

import json
from datetime import UTC, datetime
from pathlib import Path

from ..core.config import Settings
from ..core.logging import get_logger
from ..models import (
    Artifact,
    ArtifactKind,
    ExportManifest,
    ExportResult,
    ExportStatus,
    ManifestEntry,
    Meeting,
)

log = get_logger(__name__)

PRIVACY_README = """# About this folder

This folder contains a recording of a meeting and material derived from it.

Other people's voices and words are in these files. They were recorded on the
understanding that this is a personal archive. Please do not share this folder, or
anything in it, without their agreement.

Generated by Pocket.ai Studio.
"""


class StubStorageService:
    """Mirrors the Drive folder contract onto the local filesystem."""

    def __init__(self, settings: Settings) -> None:
        self.settings = settings
        self.root = settings.drive_stub_root

    # -- folder ---------------------------------------------------------------

    def _meeting_dir(self, meeting: Meeting) -> Path:
        return self.root / f"{meeting.occurred_at:%Y}" / meeting.folder_name

    async def ensure_meeting_folder(self, meeting: Meeting) -> str:
        path = self._meeting_dir(meeting)
        path.mkdir(parents=True, exist_ok=True)
        readme = path / "README.md"
        if not readme.exists():
            readme.write_text(PRIVACY_README, encoding="utf-8")
        return str(path)

    # -- manifest -------------------------------------------------------------

    def _manifest_path(self, meeting: Meeting) -> Path:
        return self._meeting_dir(meeting) / "manifest.json"

    async def read_manifest(self, meeting_id: str) -> ExportManifest | None:
        """Recover export state by scanning the tree.

        Deliberately reads from the archive rather than a database, because that is
        the property ADR-0002 claims: losing the database must be recoverable.
        """
        for path in self.root.rglob("manifest.json"):
            try:
                data = json.loads(path.read_text(encoding="utf-8"))
            except (OSError, json.JSONDecodeError):
                continue
            if data.get("meeting_id") == meeting_id:
                return ExportManifest.model_validate(data)
        return None

    def _write_manifest(self, meeting: Meeting, manifest: ExportManifest) -> None:
        self._manifest_path(meeting).write_text(
            manifest.model_dump_json(indent=2), encoding="utf-8"
        )

    # -- export ---------------------------------------------------------------

    async def export(self, meeting: Meeting, artifact: Artifact) -> ExportResult:
        folder = await self.ensure_meeting_folder(meeting)
        manifest = await self.read_manifest(meeting.id) or ExportManifest(
            meeting_id=meeting.id,
            folder_name=meeting.folder_name,
            drive_folder_id=folder,
        )

        if manifest.is_unchanged(artifact.kind, artifact.content_hash):
            log.debug("export.skip_unchanged", meeting_id=meeting.id, kind=artifact.kind.value)
            return ExportResult(
                artifact_kind=artifact.kind,
                status=ExportStatus.SKIPPED_UNCHANGED,
                drive_file_id=manifest.entry_for(artifact.kind).drive_file_id,
            )

        filename = self._filename_for(meeting, artifact)
        target = Path(folder) / filename
        target.write_bytes(artifact.content)

        manifest.upsert(
            ManifestEntry(
                artifact_kind=artifact.kind,
                filename=filename,
                drive_file_id=str(target),
                content_hash=artifact.content_hash,
                size_bytes=len(artifact.content),
                exported_at=datetime.now(UTC),
                status=ExportStatus.OK,
            )
        )
        self._write_manifest(meeting, manifest)

        log.info("export.wrote", meeting_id=meeting.id, kind=artifact.kind.value)
        return ExportResult(
            artifact_kind=artifact.kind,
            status=ExportStatus.OK,
            drive_file_id=str(target),
        )

    async def export_all(self, meeting: Meeting, artifacts: list[Artifact]) -> ExportManifest:
        for artifact in artifacts:
            await self.export(meeting, artifact)
        manifest = await self.read_manifest(meeting.id) or ExportManifest(
            meeting_id=meeting.id, folder_name=meeting.folder_name
        )
        manifest.last_full_sync = datetime.now(UTC)
        self._write_manifest(meeting, manifest)
        return manifest

    @staticmethod
    def _filename_for(meeting: Meeting, artifact: Artifact) -> str:
        if artifact.kind is ArtifactKind.AUDIO:
            suffix = Path(meeting.audio.original_filename).suffix or ".m4a"
            return f"audio{suffix}"
        return artifact.filename
